apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-openzfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-csi-openzfs