---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: openzfs.csi.k8s.io
  labels:
    app.kubernetes.io/instance: openzfs.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-openzfs
    app.kubernetes.io/name: openzfs.csi.k8s.io
    app.kubernetes.io/component: csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false
  seLinuxMount: false
  fsGroupPolicy: File